[package]
name = "isobmff-boxes"
version = "0.0.0"
description = "Catalog of ISO base media file format boxes, decoded into owned values"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
readme.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
exclude.workspace = true

[dependencies]
isobmff-core.workspace = true

[lints]
workspace = true
